FORMAT: 1A
HOST: http://docker.lancehudson.io/

# Docker Build Server

This is a API supporting a docker image build service that deeply integrates with GitHub.

## Ping [/api/v1/ping]

### Health Check [GET]

+ Response 200 (application/json)

        {
          "timestamp": 1449466367912,
          "uptime": 2.922,
          "resources": {
            "memory": {
              "rss": 63127552,
              "heapTotal": 42249216,
              "heapUsed": 29344496
            },
            "loadavg": [
              1.8544921875,
              1.87451171875,
              1.9169921875
            ]
          }
        }
        
+ Response 403 (application/json)

        {
          "errors": [
            {
              "code": "ForbiddenError",
              "title": "forbidden"
            }
          ]
        }
